// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

/*
Package database is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Player
	Session
	Cell
	Stat
	Move
	Data
*/
package database

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	Name  string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Stats *Stat      `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
	Saves []*Session `protobuf:"bytes,3,rep,name=saves" json:"saves,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetStats() *Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Player) GetSaves() []*Session {
	if m != nil {
		return m.Saves
	}
	return nil
}

type Session struct {
	Board       []*Cell `protobuf:"bytes,1,rep,name=board" json:"board,omitempty"`
	P1          *Player `protobuf:"bytes,2,opt,name=p1" json:"p1,omitempty"`
	P2          *Player `protobuf:"bytes,3,opt,name=p2" json:"p2,omitempty"`
	HistoricP1  []*Move `protobuf:"bytes,4,rep,name=historicP1" json:"historicP1,omitempty"`
	HistoricP2  []*Move `protobuf:"bytes,5,rep,name=historicP2" json:"historicP2,omitempty"`
	NbCaptureP1 int32   `protobuf:"varint,6,opt,name=nbCaptureP1" json:"nbCaptureP1,omitempty"`
	NbCaptureP2 int32   `protobuf:"varint,7,opt,name=nbCaptureP2" json:"nbCaptureP2,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetBoard() []*Cell {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Session) GetP1() *Player {
	if m != nil {
		return m.P1
	}
	return nil
}

func (m *Session) GetP2() *Player {
	if m != nil {
		return m.P2
	}
	return nil
}

func (m *Session) GetHistoricP1() []*Move {
	if m != nil {
		return m.HistoricP1
	}
	return nil
}

func (m *Session) GetHistoricP2() []*Move {
	if m != nil {
		return m.HistoricP2
	}
	return nil
}

func (m *Session) GetNbCaptureP1() int32 {
	if m != nil {
		return m.NbCaptureP1
	}
	return 0
}

func (m *Session) GetNbCaptureP2() int32 {
	if m != nil {
		return m.NbCaptureP2
	}
	return 0
}

type Cell struct {
	Value  int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Weight int32 `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *Cell) Reset()                    { *m = Cell{} }
func (m *Cell) String() string            { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()               {}
func (*Cell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cell) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Cell) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Stat struct {
	NbGame int32 `protobuf:"varint,1,opt,name=nbGame" json:"nbGame,omitempty"`
	NbWin  int32 `protobuf:"varint,2,opt,name=nbWin" json:"nbWin,omitempty"`
}

func (m *Stat) Reset()                    { *m = Stat{} }
func (m *Stat) String() string            { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()               {}
func (*Stat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Stat) GetNbGame() int32 {
	if m != nil {
		return m.NbGame
	}
	return 0
}

func (m *Stat) GetNbWin() int32 {
	if m != nil {
		return m.NbWin
	}
	return 0
}

type Move struct {
	X      int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Reflex int64 `protobuf:"varint,3,opt,name=reflex" json:"reflex,omitempty"`
}

func (m *Move) Reset()                    { *m = Move{} }
func (m *Move) String() string            { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()               {}
func (*Move) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Move) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Move) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Move) GetReflex() int64 {
	if m != nil {
		return m.Reflex
	}
	return 0
}

type Data struct {
	Players []*Player `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	Current *Session  `protobuf:"bytes,2,opt,name=current" json:"current,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Data) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Data) GetCurrent() *Session {
	if m != nil {
		return m.Current
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "database.Player")
	proto.RegisterType((*Session)(nil), "database.Session")
	proto.RegisterType((*Cell)(nil), "database.Cell")
	proto.RegisterType((*Stat)(nil), "database.Stat")
	proto.RegisterType((*Move)(nil), "database.Move")
	proto.RegisterType((*Data)(nil), "database.Data")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x4b, 0xeb, 0x30,
	0x14, 0xc6, 0x49, 0xdb, 0xb4, 0xbb, 0x67, 0x97, 0xcb, 0x35, 0x88, 0xe4, 0xb1, 0x14, 0xc1, 0xa2,
	0x50, 0x68, 0xf4, 0xc9, 0xd7, 0x09, 0x3e, 0x09, 0x23, 0x3e, 0xf8, 0x28, 0xe9, 0x16, 0x5d, 0xb1,
	0xb6, 0x25, 0xc9, 0xe6, 0xf6, 0x97, 0xf8, 0xef, 0x4a, 0xda, 0x14, 0xbb, 0xa9, 0xf8, 0xd6, 0x2f,
	0xe7, 0xf7, 0x9d, 0x34, 0xe7, 0x3b, 0x30, 0x59, 0x16, 0x59, 0xab, 0x1a, 0xd3, 0x90, 0xc9, 0x52,
	0x18, 0x51, 0x08, 0x2d, 0x93, 0x17, 0x08, 0xe7, 0x95, 0xd8, 0x49, 0x45, 0x08, 0x04, 0xb5, 0x78,
	0x95, 0x14, 0xc5, 0x28, 0xfd, 0xc3, 0xbb, 0x6f, 0x72, 0x0a, 0x58, 0x1b, 0x61, 0x34, 0xf5, 0x62,
	0x94, 0x4e, 0xd9, 0xbf, 0x6c, 0xf0, 0x65, 0xf7, 0x46, 0x18, 0xde, 0x17, 0xc9, 0x19, 0x60, 0x2d,
	0x36, 0x52, 0x53, 0x3f, 0xf6, 0xd3, 0x29, 0x3b, 0x1a, 0x51, 0x52, 0xeb, 0xb2, 0xa9, 0x79, 0x5f,
	0x4f, 0xde, 0x3d, 0x88, 0xdc, 0x91, 0x6d, 0x5d, 0x34, 0x42, 0x2d, 0x29, 0xea, 0x4c, 0xa3, 0xd6,
	0x33, 0x59, 0x55, 0xbc, 0x2f, 0x92, 0x18, 0xbc, 0x36, 0x77, 0xb7, 0xff, 0xff, 0x44, 0xfa, 0x5f,
	0xe6, 0x5e, 0x9b, 0x77, 0x04, 0xa3, 0xfe, 0x8f, 0x04, 0x23, 0x19, 0xc0, 0xaa, 0xd4, 0xa6, 0x51,
	0xe5, 0x62, 0x9e, 0xd3, 0xe0, 0xf0, 0xba, 0xbb, 0x66, 0x23, 0xf9, 0x88, 0xd8, 0xe3, 0x19, 0xc5,
	0xbf, 0xf0, 0x8c, 0xc4, 0x30, 0xad, 0x8b, 0x99, 0x68, 0xcd, 0x5a, 0xc9, 0x79, 0x4e, 0xc3, 0x18,
	0xa5, 0x98, 0x8f, 0x8f, 0xf6, 0x09, 0x46, 0xa3, 0x43, 0x82, 0x25, 0x57, 0x10, 0xd8, 0x67, 0x93,
	0x63, 0xc0, 0x1b, 0x51, 0xad, 0xfb, 0x14, 0x30, 0xef, 0x05, 0x39, 0x81, 0xf0, 0x4d, 0x96, 0xcf,
	0x2b, 0xd3, 0x4d, 0x02, 0x73, 0xa7, 0xac, 0xcb, 0xe6, 0x60, 0xeb, 0x75, 0x71, 0x3b, 0x84, 0x87,
	0xb9, 0x53, 0xb6, 0x5b, 0x5d, 0x3c, 0x94, 0xb5, 0xb3, 0xf5, 0x22, 0xb9, 0x86, 0xc0, 0xbe, 0x81,
	0xfc, 0x05, 0xb4, 0x75, 0x06, 0xb4, 0xb5, 0x6a, 0xe7, 0x38, 0xb4, 0xb3, 0x1d, 0x95, 0x7c, 0xaa,
	0xe4, 0xb6, 0x9b, 0xac, 0xcf, 0x9d, 0x4a, 0x1e, 0x21, 0xb8, 0x11, 0x46, 0x90, 0x73, 0x88, 0xda,
	0x6e, 0xc2, 0xda, 0xe5, 0xf7, 0x75, 0xf4, 0x03, 0x40, 0x2e, 0x20, 0x5a, 0xac, 0x95, 0x92, 0xb5,
	0x71, 0x41, 0x7e, 0xb3, 0x20, 0x03, 0x51, 0x84, 0xdd, 0x82, 0x5e, 0x7e, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x38, 0x67, 0x69, 0xac, 0x02, 0x00, 0x00,
}
